const members = [
  { name: "Ariston", age: 35 },
  { name: "Callias", age: 42 },
  { name: "Demetrius", age: 29 },
  { name: "Eudorus", age: 31 },
  { name: "Gorgias", age: 46 },
  { name: "Helios", age: 25 },
  { name: "Iphicrates", age: 40 },
  { name: "Leonidas", age: 50 },
  { name: "Menelaus", age: 48 },
  { name: "Nestor", age: 60 },
  { name: "Odysseus", age: 39 },
  { name: "Polydeuces", age: 32 },
  { name: "Theseus", age: 37 },
  { name: "Adrastus", age: 44 },
  { name: "Bellerophon", age: 30 },
  { name: "Castor", age: 28 },
  { name: "Diomedes", age: 35 },
  { name: "Empedocles", age: 50 },
  { name: "Ganymede", age: 20 },
  { name: "Heracles", age: 45 },
  { name: "Iolaus", age: 38 },
  { name: "Leucippus", age: 43 },
  { name: "Meleager", age: 36 },
  { name: "Neoptolemus", age: 24 },
  { name: "Orpheus", age: 47 },
  { name: "Perseus", age: 31 },
  { name: "Tantalus", age: 55 },
  { name: "Ulysses", age: 41 },
  { name: "Zenon", age: 26 },
  { name: "Alastor", age: 40 },
  { name: "Chrysippus", age: 52 },
];

const tags = [
  { name: "conquérant" },
  { name: "courageux" },
  { name: "puissant" },
  { name: "vaillant" },
  { name: "stratège" },
  { name: "beau" },
  { name: "tragique" },
  { name: "philosophe" },
  { name: "savant" },
  { name: "intelligent" },
  { name: "chanceux" },
];

const memberTags = [
  { member_id: 1, tag_id: 1 },
  { member_id: 1, tag_id: 2 },
  { member_id: 2, tag_id: 3 },
  { member_id: 2, tag_id: 4 },
  { member_id: 3, tag_id: 5 },
  { member_id: 3, tag_id: 6 },
  { member_id: 4, tag_id: 7 },
  { member_id: 4, tag_id: 8 },
  { member_id: 5, tag_id: 9 },
  { member_id: 5, tag_id: 10 },
  { member_id: 6, tag_id: 1 },
  { member_id: 6, tag_id: 2 },
  { member_id: 7, tag_id: 3 },
  { member_id: 7, tag_id: 4 },
  { member_id: 8, tag_id: 5 },
  { member_id: 8, tag_id: 6 },
  { member_id: 9, tag_id: 7 },
  { member_id: 9, tag_id: 8 },
  { member_id: 10, tag_id: 9 },
  { member_id: 10, tag_id: 10 },
  { member_id: 11, tag_id: 1 },
  { member_id: 11, tag_id: 2 },
  { member_id: 12, tag_id: 3 },
  { member_id: 12, tag_id: 4 },
  { member_id: 13, tag_id: 5 },
  { member_id: 13, tag_id: 6 },
  { member_id: 14, tag_id: 7 },
  { member_id: 14, tag_id: 8 },
  { member_id: 15, tag_id: 9 },
  { member_id: 15, tag_id: 10 },
  { member_id: 16, tag_id: 1 },
  { member_id: 16, tag_id: 2 },
  { member_id: 17, tag_id: 3 },
  { member_id: 17, tag_id: 4 },
  { member_id: 18, tag_id: 5 },
  { member_id: 18, tag_id: 6 },
  { member_id: 19, tag_id: 7 },
  { member_id: 19, tag_id: 8 },
  { member_id: 20, tag_id: 9 },
  { member_id: 20, tag_id: 10 },
  { member_id: 21, tag_id: 1 },
  { member_id: 21, tag_id: 2 },
  { member_id: 22, tag_id: 3 },
  { member_id: 22, tag_id: 4 },
  { member_id: 23, tag_id: 5 },
  { member_id: 23, tag_id: 6 },
  { member_id: 24, tag_id: 7 },
  { member_id: 24, tag_id: 8 },
  { member_id: 25, tag_id: 9 },
  { member_id: 25, tag_id: 10 },
  { member_id: 26, tag_id: 1 },
  { member_id: 26, tag_id: 2 },
  { member_id: 27, tag_id: 3 },
  { member_id: 27, tag_id: 4 },
  { member_id: 28, tag_id: 5 },
  { member_id: 28, tag_id: 6 },
  { member_id: 29, tag_id: 7 },
  { member_id: 29, tag_id: 8 },
  { member_id: 30, tag_id: 9 },
  { member_id: 30, tag_id: 10 },
  { member_id: 31, tag_id: 1 },
  { member_id: 31, tag_id: 2 },
];

module.exports = {
  members,
  tags,
  memberTags,
};
