GET http://localhost:5000/members

###
GET http://localhost:5000/members/1

###
POST http://localhost:5000/members
Content-Type: application/json

{
    "name": "Mouns",
    "age": 24,
    "tags": [
        {
            "tag_id": 4
        },
        {
            "tag_id": 6
        }
    ]
}

###
PUT http://localhost:5000/members/33
Content-Type: application/json

{
    "name": "Mouns",
    "age": 24
}

###
DELETE http://localhost:5000/members/33